### ISSUE TITLE
REST Edit Datasource TypeError - how do we specific NoContent reponse?

### ISSUE THREAD

**Issue by joshbooker** [akorchev/radzen#47]
Repro:
Create New REST connection
Add Schema
Name it 'NoContent'
do not add any properties
Click Next
Add Resource and operation using NoContent Response
Click Next
ReferenceError: responseSchema is not defined
okay let me delete the schema or add a property or something

Boom, stuck  can go back but cannot go forward, must cancel

At one point I got this:

`[2017-06-02 13:57:41:0565] [error] { __zone_symbol__currentTask: 
   { _state: 'notScheduled',
     _zone: 
      { _name: '<root>',
        _parent: null,
        _properties: {},
        _zoneDelegate: [Object] },
     _zoneDelegates: null,
     cancelFn: null,
     runCount: 0,
     source: 'Promise.then',
     type: 'microTask' } }
[2017-06-02 13:58:01:0071] [error] ReferenceError: responseSchema is not defined
    at file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:32:3694887
    at m (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:6:1795)
    at bs (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:6:42720)
    at file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:32:3694779
    at file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:6:19976
    at file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:6:26794
    at na (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:6:17237)
    at file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:6:26599
    at Ga (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:6:19948)
    at bs (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:6:42720)
    at file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:32:3694707
    at file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:6:19976
    at file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:6:26794
    at na (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:6:17237)
    at file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:6:26599
[2017-06-02 13:58:04:0965] [error] TypeError: Cannot read property 'name' of undefined
    at t.value (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:32:3712606)
    at d._renderValidatedComponentWithoutOwnerOrContext (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:279423)
    at d._renderValidatedComponent (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:279550)
    at d.performInitialMount (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:275349)
    at d.mountComponent (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:274395)
    at Object.mountComponent (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:12:59767)
    at Object.updateChildren (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:272006)
    at h._reconcilerUpdateChildren (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:306419)
    at h._updateChildren (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:307168)
    at h.updateChildren (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:307066)
    at h._updateDOMChildren (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:289904)
    at h.updateComponent (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:288128)
    at h.receiveComponent (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:287612)
    at Object.receiveComponent (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:12:60161)
    at Object.updateChildren (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:271887)
[2017-06-02 13:58:15:0020] [error] TypeError: Cannot read property 'name' of undefined
    at t.value (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:32:3712606)
    at d._renderValidatedComponentWithoutOwnerOrContext (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:279423)
    at d._renderValidatedComponent (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:279550)
    at d.performInitialMount (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:275349)
    at d.mountComponent (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:274395)
    at Object.mountComponent (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:12:59767)
    at Object.updateChildren (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:272006)
    at h._reconcilerUpdateChildren (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:306419)
    at h._updateChildren (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:307168)
    at h.updateChildren (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:307066)
    at h._updateDOMChildren (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:289904)
    at h.updateComponent (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:288128)
    at h.receiveComponent (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:287612)
    at Object.receiveComponent (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:12:60161)
    at Object.updateChildren (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:271887)
[2017-06-02 13:58:31:0899] [error] TypeError: Cannot read property 'name' of undefined
    at t.value (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:32:3712606)
    at d._renderValidatedComponentWithoutOwnerOrContext (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:279423)
    at d._renderValidatedComponent (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:279550)
    at d.performInitialMount (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:275349)
    at d.mountComponent (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:274395)
    at Object.mountComponent (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:12:59767)
    at Object.updateChildren (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:272006)
    at h._reconcilerUpdateChildren (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:306419)
    at h._updateChildren (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:307168)
    at h.updateChildren (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:307066)
    at h._updateDOMChildren (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:289904)
    at h.updateComponent (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:288128)
    at h.receiveComponent (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:287612)
    at Object.receiveComponent (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:12:60161)
    at Object.updateChildren (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:271887)
[2017-06-02 13:58:43:0499] [error] TypeError: Cannot read property 'name' of undefined
    at t.value (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:32:3712606)
    at d._renderValidatedComponentWithoutOwnerOrContext (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:279423)
    at d._renderValidatedComponent (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:279550)
    at d.performInitialMount (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:275349)
    at d.mountComponent (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:274395)
    at Object.mountComponent (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:12:59767)
    at Object.updateChildren (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:272006)
    at h._reconcilerUpdateChildren (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:306419)
    at h._updateChildren (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:307168)
    at h.updateChildren (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:307066)
    at h._updateDOMChildren (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:289904)
    at h.updateComponent (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:288128)
    at h.receiveComponent (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:287612)
    at Object.receiveComponent (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:12:60161)
    at Object.updateChildren (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:271887)
[2017-06-02 13:58:45:0283] [error] TypeError: Cannot read property 'name' of undefined
    at t.value (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:32:3712606)
    at d._renderValidatedComponentWithoutOwnerOrContext (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:279423)
    at d._renderValidatedComponent (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:279550)
    at d.performInitialMount (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:275349)
    at d.mountComponent (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:274395)
    at Object.mountComponent (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:12:59767)
    at Object.updateChildren (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:272006)
    at h._reconcilerUpdateChildren (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:306419)
    at h._updateChildren (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:307168)
    at h.updateChildren (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:307066)
    at h._updateDOMChildren (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:289904)
    at h.updateComponent (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:288128)
    at h.receiveComponent (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:287612)
    at Object.receiveComponent (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:12:60161)
    at Object.updateChildren (file:///C:/Program%20Files/Radzen/resources/app.asar/static/renderer.js:40:271887)`

Thanks in advance.

**Comment by joshbooker** [comment]
It seems the NoContent Schema may not be the problem.  I get this error upon adding a patch method having a body parameter of type Category.  As far as I can tell the swagger in my meta\data\<RestDataSource>.json is fine:

`{
  "basePath": "/",
  "definitions": {
    "Category": {
      "properties": {
        "CategoryID": {
          "format": "int32",
          "type": "integer"
        },
        "CategoryName": {
          "type": "string"
        }
      }
    },
    "NoContent": {
      "properties": {}
    }
  },
  "host": "northwindapi2.azurewebsites.net",
  "info": {
    "title": "NwRest4",
    "x-type": "rest"
  },
  "paths": {
    "Categories": {
      "get": {
        "operationId": "GetCategories",
        "parameters": [
          {
            "in": "query",
            "name": "$filter",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "items": {
                "$ref": "#/definitions/Category"
              },
              "type": "array"
            }
          }
        }
      }
    },
    "Categories({CategoryID})": {
      "patch": {
        "operationId": "PatchCategory",
        "parameters": [
          {
            "in": "path",
            "name": "CategoryID",
            "type": "integer"
          },
          {
            "in": "body",
            "name": "Category",
            "schema": {
              "$ref": "#/definitions/Category"
            }
          }
        ],
        "responses": {
          "204": {
            "schema": {
              "$ref": "#/definitions/NoContent"
            }
          }
        }
      }
    }
  },
  "schemes": [
    "https"
  ]
}`

**Comment by akorchev** [comment]
We will investigate and fix this issue. Thanks!

**Comment by akorchev** [comment]
Should also be fixed with 1.5.
