### ISSUE TITLE
System.InvalidOperationException: No media types found in 'Microsoft.AspNetCore.OData.Formatter.ODataOutputFormatter.SupportedMediaTypes'. Add at least one media type to the list of supported media types.

### ISSUE THREAD

**Issue by adelchi** [akorchev/radzen#57]
Hi

Was playing around with your nuget-package Microsoft.AspNetCore.OData.Radzen and stumbled upon the exception below while adding Swagger/Swashbuckle.

It might be a similar problem like here:
https://github.com/WebApiContrib/WebAPIContrib.Core/pull/94 

If you want i can try help fixing it :)

`System.InvalidOperationException: No media types found in 'Microsoft.AspNetCore.OData.Formatter.ODataOutputFormatter.SupportedMediaTypes'. Add at least one media type to the list of supported media types.
   at Microsoft.AspNetCore.Mvc.Formatters.OutputFormatter.GetSupportedContentTypes(String contentType, Type objectType)
   at Microsoft.AspNetCore.Mvc.ApiExplorer.DefaultApiDescriptionProvider.GetApiResponseTypes(ControllerActionDescriptor action, IApiResponseMetadataProvider[] responseMetadataAttributes, Type type)
   at Microsoft.AspNetCore.Mvc.ApiExplorer.DefaultApiDescriptionProvider.CreateApiDescription(ControllerActionDescriptor action, String httpMethod, String groupName)
   at Microsoft.AspNetCore.Mvc.ApiExplorer.DefaultApiDescriptionProvider.OnProvidersExecuting(ApiDescriptionProviderContext context)
   at Microsoft.AspNetCore.Mvc.ApiExplorer.ApiDescriptionGroupCollectionProvider.GetCollection(ActionDescriptorCollection actionDescriptors)
   at Microsoft.AspNetCore.Mvc.ApiExplorer.ApiDescriptionGroupCollectionProvider.get_ApiDescriptionGroups()
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath, String[] schemes)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.<Invoke>d__6.MoveNext()`

**Comment by akorchev** [comment]
I've made the [repository](https://github.com/akorchev/odata) public. That's probably the only thing we can do. Unfortunately the fate of OData in .NET Core is unknown.

**Comment by adelchi** [comment]
Thanks. I'll see what I can do :)
