### ISSUE TITLE
Generating SSL Certificate

### ISSUE THREAD

**Issue by leam77** [akorchev/radzen#71]
Hello, how can I solve the following, thanks:

ng-cli: Generating SSL Certificate

ng-cli: ENOENT: no such file or directory, open 'C:\Program Files\Radzen\resources\node_modules\webpack-dev-server\ssl\server.pem'

ng-cli: Error: ENOENT: no such file or directory, open 'C:\Program Files\Radzen\resources\node_modules\webpack-dev-server\ssl\server.pem'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.writeFileSync (fs.js:1233:33)
    at new Server (C:\Program Files\Radzen\resources\node_modules\webpack-dev-server\lib\Server.js:394:7)
    at Class.run (C:\Program Files\Radzen\resources\node_modules\@angular\cli\tasks\serve.js:194:24)
    at check_port_1.checkPort.then.port (C:\Program Files\Radzen\resources\node_modules\@angular\cli\commands\serve.js:114:26)
    at process._tickCallback (internal/process/next_tick.js:103:7)

ng-cli: Exited with code: 1
radzen: undefined

**Comment by akorchev** [comment]
Hi,

What version of Radzen are you using? The `Generating SSL Certificate` message hasn't been logged in the console for a few versions and we have fixed a couple of issues related to HTTPS. 

Please try downloading the latest version. If the error remains I would ask you to zip the meta directory of the app and send it to info@radzen.com so we can troubleshoot.

**Comment by akorchev** [comment]
Fixed.
